// Code generated by "stringer -type=Type message.go"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Open-1]
	_ = x[Update-2]
	_ = x[Keepalive-4]
}

const (
	_Type_name_0 = "OpenUpdate"
	_Type_name_1 = "Keepalive"
)

var (
	_Type_index_0 = [...]uint8{0, 4, 10}
)

func (i Type) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case i == 4:
		return _Type_name_1
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
