// Code generated by "stringer -type=AttrType pathattribute.go"; DO NOT EDIT.

package pab

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ORG-1]
	_ = x[ASP-2]
	_ = x[NHP-3]
}

const _AttrType_name = "ORGASPNHP"

var _AttrType_index = [...]uint8{0, 3, 6, 9}

func (i AttrType) String() string {
	i -= 1
	if i >= AttrType(len(_AttrType_index)-1) {
		return "AttrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AttrType_name[_AttrType_index[i]:_AttrType_index[i+1]]
}
