// Code generated by "stringer -type=Origin pathattribute.go"; DO NOT EDIT.

package pab

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Igp-0]
	_ = x[Egp-1]
	_ = x[Incomplete-2]
}

const _Origin_name = "IgpEgpIncomplete"

var _Origin_index = [...]uint8{0, 3, 6, 16}

func (i Origin) String() string {
	if i >= Origin(len(_Origin_index)-1) {
		return "Origin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Origin_name[_Origin_index[i]:_Origin_index[i+1]]
}
